repository : YoussefRaafatNasry/YoussefRaafatNasry.github.io
team_site  : https://zero-based.github.io/
resume     : https://docs.google.com/document/d/1IUDXlrmKFvhkr0-P2bP3NlsNMESeCzCvJoOiXRYIRz4/export?format=pdf